packages:
  - packages/*
  - play
  - docs

catalog:
  '@antfu/eslint-config': ^6.4.1
  '@changesets/cli': ^2.29.8
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@element-plus/icons-vue': ^2.3.2
  '@falconix/fep': ^1.1.0
  '@types/fs-extra': 11.0.4
  '@types/node': ^24.10.1
  '@types/semver': ^7.7.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/tsconfig': ^0.8.1
  axios: ^1.13.2
  eslint: ^9.39.1
  eslint-plugin-format: ^1.1.0
  fs-extra: ^11.3.2
  globby: ^16.0.0
  husky: ^9.1.7
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  postcss: ^8.5.6
  promise-portal: ^1.2.1
  sass: ^1.97.3
  sass-embedded: ^1.93.3
  semver: ^7.7.3
  tsdown: ^0.16.8
  turbo: ^2.6.3
  typescript: ~5.9.3
  unplugin-auto-import: ^20.3.0
  unplugin-vue: ^7.1.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.2.6
  vite-plugin-lib-inject-css: ^2.2.2
  vite-plugin-pages: ^0.33.2
  vite-plugin-static-copy: ^3.2.0
  vitepress: ^2.0.0-alpha.15
  vitepress-demo-plugin: ^1.5.1
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.8
  wujie-vue3: ^1.0.29

catalogMode: strict

cleanupUnusedCatalogs: true

shellEmulator: true
