export { emitEvent as $emit } from './hooks/emit-event'
export { onEvent as $on } from './hooks/on-event'
export * from './hooks/on-micro-app-activated'
export * from './hooks/use-micro-app'
export * from './hooks/use-micro-app-props'
export type * from './types/global.d.ts'
