/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElMessage: typeof import('@falconix/fep/es').ElMessage
  const ElMessageBox: typeof import('@falconix/fep/es').ElMessageBox
}
