/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('@falconix/fep/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('@falconix/fep/es')['ElBreadcrumbItem']
    ElButton: typeof import('@falconix/fep/es')['ElButton']
    ElConfigProvider: typeof import('@falconix/fep/es')['ElConfigProvider']
    ElDatePicker: typeof import('@falconix/fep/es')['ElDatePicker']
    ElDrawer: typeof import('@falconix/fep/es')['ElDrawer']
    ElInput: typeof import('@falconix/fep/es')['ElInput']
    ElSwitch: typeof import('@falconix/fep/es')['ElSwitch']
    ElTable: typeof import('@falconix/fep/es')['ElTable']
    ElTableColumn: typeof import('@falconix/fep/es')['ElTableColumn']
  }
}
