/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('@falconix/fep/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('@falconix/fep/es')['ElBreadcrumbItem']
    ElButton: typeof import('@falconix/fep/es')['ElButton']
    ElCascader: typeof import('@falconix/fep/es')['ElCascader']
    ElConfigProvider: typeof import('@falconix/fep/es')['ElConfigProvider']
    ElDatePicker: typeof import('@falconix/fep/es')['ElDatePicker']
    ElDatePickerPanel: typeof import('@falconix/fep/es')['ElDatePickerPanel']
    ElDialog: typeof import('@falconix/fep/es')['ElDialog']
    ElDrawer: typeof import('@falconix/fep/es')['ElDrawer']
    ElDropdown: typeof import('@falconix/fep/es')['ElDropdown']
    ElDropdownItem: typeof import('@falconix/fep/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('@falconix/fep/es')['ElDropdownMenu']
    ElIcon: typeof import('@falconix/fep/es')['ElIcon']
    ElInput: typeof import('@falconix/fep/es')['ElInput']
    ElPopover: typeof import('@falconix/fep/es')['ElPopover']
    ElSelect: typeof import('@falconix/fep/es')['ElSelect']
    ElSwitch: typeof import('@falconix/fep/es')['ElSwitch']
    ElTable: typeof import('@falconix/fep/es')['ElTable']
    ElTableColumn: typeof import('@falconix/fep/es')['ElTableColumn']
    ElTabPane: typeof import('@falconix/fep/es')['ElTabPane']
    ElTabs: typeof import('@falconix/fep/es')['ElTabs']
    ElTooltip: typeof import('@falconix/fep/es')['ElTooltip']
  }
}
