/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('@falconix/fep/es')['ElAlert']
    ElButton: typeof import('@falconix/fep/es')['ElButton']
    ElCol: typeof import('@falconix/fep/es')['ElCol']
    ElForm: typeof import('@falconix/fep/es')['ElForm']
    ElFormItem: typeof import('@falconix/fep/es')['ElFormItem']
    ElIcon: typeof import('@falconix/fep/es')['ElIcon']
    ElInput: typeof import('@falconix/fep/es')['ElInput']
    ElMenu: typeof import('@falconix/fep/es')['ElMenu']
    ElMenuItem: typeof import('@falconix/fep/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('@falconix/fep/es')['ElMenuItemGroup']
    ElRow: typeof import('@falconix/fep/es')['ElRow']
    ElSpace: typeof import('@falconix/fep/es')['ElSpace']
    ElSubMenu: typeof import('@falconix/fep/es')['ElSubMenu']
    ElTag: typeof import('@falconix/fep/es')['ElTag']
    FAutoSave: typeof import('@falconix/auto-save')['FAutoSave']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ElAlert: typeof import('@falconix/fep/es')['ElAlert']
  const ElButton: typeof import('@falconix/fep/es')['ElButton']
  const ElCol: typeof import('@falconix/fep/es')['ElCol']
  const ElForm: typeof import('@falconix/fep/es')['ElForm']
  const ElFormItem: typeof import('@falconix/fep/es')['ElFormItem']
  const ElIcon: typeof import('@falconix/fep/es')['ElIcon']
  const ElInput: typeof import('@falconix/fep/es')['ElInput']
  const ElMenu: typeof import('@falconix/fep/es')['ElMenu']
  const ElMenuItem: typeof import('@falconix/fep/es')['ElMenuItem']
  const ElMenuItemGroup: typeof import('@falconix/fep/es')['ElMenuItemGroup']
  const ElRow: typeof import('@falconix/fep/es')['ElRow']
  const ElSpace: typeof import('@falconix/fep/es')['ElSpace']
  const ElSubMenu: typeof import('@falconix/fep/es')['ElSubMenu']
  const ElTag: typeof import('@falconix/fep/es')['ElTag']
  const FAutoSave: typeof import('@falconix/auto-save')['FAutoSave']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}