/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('@falconix/fep/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('@falconix/fep/es')['ElBreadcrumbItem']
    ElButton: typeof import('@falconix/fep/es')['ElButton']
    ElCascader: typeof import('@falconix/fep/es')['ElCascader']
    ElConfigProvider: typeof import('@falconix/fep/es')['ElConfigProvider']
    ElDatePicker: typeof import('@falconix/fep/es')['ElDatePicker']
    ElDatePickerPanel: typeof import('@falconix/fep/es')['ElDatePickerPanel']
    ElDialog: typeof import('@falconix/fep/es')['ElDialog']
    ElDrawer: typeof import('@falconix/fep/es')['ElDrawer']
    ElDropdown: typeof import('@falconix/fep/es')['ElDropdown']
    ElDropdownItem: typeof import('@falconix/fep/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('@falconix/fep/es')['ElDropdownMenu']
    ElForm: typeof import('@falconix/fep/es')['ElForm']
    ElFormItem: typeof import('@falconix/fep/es')['ElFormItem']
    ElIcon: typeof import('@falconix/fep/es')['ElIcon']
    ElInput: typeof import('@falconix/fep/es')['ElInput']
    ElPopover: typeof import('@falconix/fep/es')['ElPopover']
    ElSelect: typeof import('@falconix/fep/es')['ElSelect']
    ElSwitch: typeof import('@falconix/fep/es')['ElSwitch']
    ElTable: typeof import('@falconix/fep/es')['ElTable']
    ElTableColumn: typeof import('@falconix/fep/es')['ElTableColumn']
    ElTabPane: typeof import('@falconix/fep/es')['ElTabPane']
    ElTabs: typeof import('@falconix/fep/es')['ElTabs']
    ElTooltip: typeof import('@falconix/fep/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ElBreadcrumb: typeof import('@falconix/fep/es')['ElBreadcrumb']
  const ElBreadcrumbItem: typeof import('@falconix/fep/es')['ElBreadcrumbItem']
  const ElButton: typeof import('@falconix/fep/es')['ElButton']
  const ElCascader: typeof import('@falconix/fep/es')['ElCascader']
  const ElConfigProvider: typeof import('@falconix/fep/es')['ElConfigProvider']
  const ElDatePicker: typeof import('@falconix/fep/es')['ElDatePicker']
  const ElDatePickerPanel: typeof import('@falconix/fep/es')['ElDatePickerPanel']
  const ElDialog: typeof import('@falconix/fep/es')['ElDialog']
  const ElDrawer: typeof import('@falconix/fep/es')['ElDrawer']
  const ElDropdown: typeof import('@falconix/fep/es')['ElDropdown']
  const ElDropdownItem: typeof import('@falconix/fep/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('@falconix/fep/es')['ElDropdownMenu']
  const ElForm: typeof import('@falconix/fep/es')['ElForm']
  const ElFormItem: typeof import('@falconix/fep/es')['ElFormItem']
  const ElIcon: typeof import('@falconix/fep/es')['ElIcon']
  const ElInput: typeof import('@falconix/fep/es')['ElInput']
  const ElPopover: typeof import('@falconix/fep/es')['ElPopover']
  const ElSelect: typeof import('@falconix/fep/es')['ElSelect']
  const ElSwitch: typeof import('@falconix/fep/es')['ElSwitch']
  const ElTable: typeof import('@falconix/fep/es')['ElTable']
  const ElTableColumn: typeof import('@falconix/fep/es')['ElTableColumn']
  const ElTabPane: typeof import('@falconix/fep/es')['ElTabPane']
  const ElTabs: typeof import('@falconix/fep/es')['ElTabs']
  const ElTooltip: typeof import('@falconix/fep/es')['ElTooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}